// Generates src/il/table.rs from System.Reflection.Emit.OpCodes.
//
// The opcode table is the one place where a transcription slip would be both
// easy to make and hard to notice, so it is derived from the runtime's own
// table rather than typed in by hand. Run from the repository root:
//
//     dotnet run --project tools/gen-opcodes > src/il/table.rs
//
// The output is checked in; regenerate it only when this generator changes.

using System.Reflection;
using System.Reflection.Emit;
using System.Text;

var fields = typeof(OpCodes)
    .GetFields(BindingFlags.Public | BindingFlags.Static)
    .Where(f => f.FieldType == typeof(OpCode))
    .Select(f => (OpCode)f.GetValue(null)!)
    .Where(o => OpCodeTypeName(o.OpCodeType) != null)
    .Select(o => new Row(
        o.Name!,
        o.Size,
        Encoding2(o),
        OperandName(o.OperandType),
        PopName(o.StackBehaviourPop),
        PushName(o.StackBehaviourPush),
        FlowName(o.FlowControl),
        OpCodeTypeName(o.OpCodeType)!))
    .Concat(new[]
    {
        // `no.` is defined by ECMA-335 III.2.2 but absent from
        // System.Reflection.Emit.OpCodes, so it is supplied here. Its operand
        // is an unsigned int8 bitmask of the checks to skip.
        new Row("no.", 2, 0xFE19, "ShortInlineI", "Pop0", "Push0", "Meta", "Prefix"),
    })
    .OrderBy(o => o.Size)
    .ThenBy(o => o.Encoding)
    .ToList();

var names = fields.ToDictionary(o => o.Name, o => Variant(o.Name));

var w = new StringBuilder();
w.AppendLine("// @generated by tools/gen-opcodes from System.Reflection.Emit.OpCodes.");
w.AppendLine("// Do not edit by hand; run `dotnet run --project tools/gen-opcodes > src/il/table.rs`.");
w.AppendLine("//");
w.AppendLine("// Every row corresponds to one entry of ECMA-335 Partition VI, Annex C.");
w.AppendLine();
w.AppendLine("use super::{FlowControl, OpCodeInfo, OpCodeKind, OperandKind, StackBehaviourPop, StackBehaviourPush};");
w.AppendLine();

// The opcode enum.
w.AppendLine("/// Every CIL opcode and prefix defined by ECMA-335 Partition VI, Annex C.");
w.AppendLine("///");
w.AppendLine("/// Variants are named after the canonical mnemonic with the dots removed and");
w.AppendLine("/// each component capitalised, so `conv.ovf.i1.un` is `ConvOvfI1Un` and the");
w.AppendLine("/// `constrained.` prefix is `Constrained`.");
w.AppendLine("#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]");
w.AppendLine("#[cfg_attr(feature = \"serde\", derive(serde::Serialize, serde::Deserialize))]");
w.AppendLine("#[repr(u16)]");
w.AppendLine("#[allow(missing_docs)]");
w.AppendLine("#[non_exhaustive]");
w.AppendLine("pub enum OpCode {");
for (var i = 0; i < fields.Count; i++)
{
    w.AppendLine($"    {names[fields[i].Name]} = {i},");
}
w.AppendLine("}");
w.AppendLine();

w.AppendLine("/// The number of opcodes and prefixes in the table.");
w.AppendLine($"pub const OPCODE_COUNT: usize = {fields.Count};");
w.AppendLine();

w.AppendLine("/// Every opcode, in table order.");
w.AppendLine("pub const ALL_OPCODES: [OpCode; OPCODE_COUNT] = [");
foreach (var o in fields)
{
    w.AppendLine($"    OpCode::{names[o.Name]},");
}
w.AppendLine("];");
w.AppendLine();

w.AppendLine("pub(crate) static OPCODE_INFO: [OpCodeInfo; OPCODE_COUNT] = [");
foreach (var o in fields)
{
    var b0 = o.Size == 1 ? o.Encoding & 0xFF : 0xFE;
    var b1 = o.Size == 1 ? 0 : o.Encoding & 0xFF;
    w.AppendLine("    OpCodeInfo {");
    w.AppendLine($"        name: \"{o.Name}\",");
    w.AppendLine($"        encoding: [0x{b0:X2}, 0x{b1:X2}],");
    w.AppendLine($"        size: {o.Size},");
    w.AppendLine($"        operand: OperandKind::{o.Operand},");
    w.AppendLine($"        pop: StackBehaviourPop::{o.Pop},");
    w.AppendLine($"        push: StackBehaviourPush::{o.Push},");
    w.AppendLine($"        flow: FlowControl::{o.Flow},");
    w.AppendLine($"        kind: OpCodeKind::{o.Kind},");
    w.AppendLine("    },");
}
w.AppendLine("];");
w.AppendLine();

// One-byte decode table.
w.AppendLine("/// Decodes a single-byte opcode.");
w.AppendLine("pub(crate) const fn decode_one(byte: u8) -> Option<OpCode> {");
w.AppendLine("    match byte {");
foreach (var o in fields.Where(o => o.Size == 1).OrderBy(o => o.Encoding))
{
    w.AppendLine($"        0x{o.Encoding & 0xFF:X2} => Some(OpCode::{names[o.Name]}),");
}
w.AppendLine("        _ => None,");
w.AppendLine("    }");
w.AppendLine("}");
w.AppendLine();

w.AppendLine("/// Decodes the second byte of a `0xFE`-escaped opcode.");
w.AppendLine("pub(crate) const fn decode_two(byte: u8) -> Option<OpCode> {");
w.AppendLine("    match byte {");
foreach (var o in fields.Where(o => o.Size == 2).OrderBy(o => o.Encoding))
{
    w.AppendLine($"        0x{o.Encoding & 0xFF:X2} => Some(OpCode::{names[o.Name]}),");
}
w.AppendLine("        _ => None,");
w.AppendLine("    }");
w.AppendLine("}");
w.AppendLine();

// canonical()
w.AppendLine("/// Maps a short or macro encoding to its general-purpose equivalent.");
w.AppendLine("pub(crate) const fn canonical_of(op: OpCode) -> OpCode {");
w.AppendLine("    match op {");
foreach (var o in fields)
{
    var canon = Canonical(o.Name);
    if (canon == o.Name || !names.ContainsKey(canon))
    {
        continue;
    }
    w.AppendLine($"        OpCode::{names[o.Name]} => OpCode::{names[canon]},");
}
w.AppendLine("        other => other,");
w.AppendLine("    }");
w.AppendLine("}");
w.AppendLine();

// Implied operands for the macro forms.
w.AppendLine("/// The local or argument index a macro encoding implies.");
w.AppendLine("pub(crate) const fn implied_var(op: OpCode) -> Option<u16> {");
w.AppendLine("    match op {");
foreach (var o in fields)
{
    var value = ImpliedIndex(o.Name);
    if (value is not null && !o.Name.StartsWith("ldc."))
    {
        w.AppendLine($"        OpCode::{names[o.Name]} => Some({value}),");
    }
}
w.AppendLine("        _ => None,");
w.AppendLine("    }");
w.AppendLine("}");
w.AppendLine();

w.AppendLine("/// The constant an `ldc.i4.*` macro encoding implies.");
w.AppendLine("pub(crate) const fn implied_i32(op: OpCode) -> Option<i32> {");
w.AppendLine("    match op {");
foreach (var o in fields.Where(o => o.Name.StartsWith("ldc.i4.") && o.Name != "ldc.i4.s"))
{
    var suffix = o.Name["ldc.i4.".Length..];
    var value = suffix == "m1" ? "-1" : suffix;
    w.AppendLine($"        OpCode::{names[o.Name]} => Some({value}),");
}
w.AppendLine("        _ => None,");
w.AppendLine("    }");
w.AppendLine("}");

Console.Out.Write(w.ToString().ReplaceLineEndings("\n"));
Console.Error.WriteLine($"generated {fields.Count} opcodes");

static int Encoding2(OpCode o) => (ushort)o.Value;

static string Variant(string name)
{
    var sb = new StringBuilder();
    foreach (var part in name.Split('.', StringSplitOptions.RemoveEmptyEntries))
    {
        sb.Append(char.ToUpperInvariant(part[0]));
        sb.Append(part[1..]);
    }
    return sb.ToString();
}

static string Canonical(string name)
{
    if (name.EndsWith(".s", StringComparison.Ordinal))
    {
        return name[..^2];
    }
    if (name.StartsWith("ldc.i4.", StringComparison.Ordinal))
    {
        return "ldc.i4";
    }
    foreach (var prefix in new[] { "ldarg.", "ldloc.", "stloc.", "ldarga.", "starg.", "ldloca." })
    {
        if (name.StartsWith(prefix, StringComparison.Ordinal) && name[prefix.Length..].All(char.IsDigit))
        {
            return prefix[..^1];
        }
    }
    return name;
}

static string? ImpliedIndex(string name)
{
    foreach (var prefix in new[] { "ldarg.", "ldloc.", "stloc." })
    {
        if (name.StartsWith(prefix, StringComparison.Ordinal))
        {
            var suffix = name[prefix.Length..];
            if (suffix.Length > 0 && suffix.All(char.IsDigit))
            {
                return suffix;
            }
        }
    }
    return null;
}

static string OperandName(OperandType t) => t switch
{
    OperandType.InlineBrTarget => "InlineBrTarget",
    OperandType.InlineField => "InlineField",
    OperandType.InlineI => "InlineI",
    OperandType.InlineI8 => "InlineI8",
    OperandType.InlineMethod => "InlineMethod",
    OperandType.InlineNone => "InlineNone",
    OperandType.InlineR => "InlineR",
    OperandType.InlineSig => "InlineSig",
    OperandType.InlineString => "InlineString",
    OperandType.InlineSwitch => "InlineSwitch",
    OperandType.InlineTok => "InlineTok",
    OperandType.InlineType => "InlineType",
    OperandType.InlineVar => "InlineVar",
    OperandType.ShortInlineBrTarget => "ShortInlineBrTarget",
    OperandType.ShortInlineI => "ShortInlineI",
    OperandType.ShortInlineR => "ShortInlineR",
    OperandType.ShortInlineVar => "ShortInlineVar",
    _ => throw new NotSupportedException($"operand type {t}"),
};

static string PopName(StackBehaviour b) => Join(b.ToString(), "pop");

static string PushName(StackBehaviour b) => Join(b.ToString(), "push");

static string Join(string value, string verb)
{
    var sb = new StringBuilder();
    foreach (var part in value.Split('_'))
    {
        var lower = part.ToLowerInvariant();
        sb.Append(lower switch
        {
            "pop0" => "Pop0",
            "pop1" => "Pop1",
            "popi" => "PopI",
            "popi8" => "PopI8",
            "popr4" => "PopR4",
            "popr8" => "PopR8",
            "popref" => "PopRef",
            "varpop" => "VarPop",
            "push0" => "Push0",
            "push1" => "Push1",
            "pushi" => "PushI",
            "pushi8" => "PushI8",
            "pushr4" => "PushR4",
            "pushr8" => "PushR8",
            "pushref" => "PushRef",
            "varpush" => "VarPush",
            _ => throw new NotSupportedException($"{verb} behaviour {part}"),
        });
    }
    return sb.ToString();
}

static string FlowName(FlowControl f) => f switch
{
    FlowControl.Branch => "Branch",
    FlowControl.Break => "Break",
    FlowControl.Call => "Call",
    FlowControl.Cond_Branch => "CondBranch",
    FlowControl.Meta => "Meta",
    FlowControl.Next => "Next",
    FlowControl.Return => "Return",
    FlowControl.Throw => "Throw",
    _ => throw new NotSupportedException($"flow control {f}"),
};

static string? OpCodeTypeName(OpCodeType t) => t switch
{
    OpCodeType.Macro => "Macro",
    OpCodeType.Objmodel => "ObjModel",
    OpCodeType.Prefix => "Prefix",
    OpCodeType.Primitive => "Primitive",
    // `Nternal` marks the `prefix1`..`prefix7` placeholders, which are not
    // encodable instructions; `0xFE` is the escape byte, not an opcode.
    _ => null,
};

/// One row of the generated opcode table.
record Row(
    string Name,
    int Size,
    int Encoding,
    string Operand,
    string Pop,
    string Push,
    string Flow,
    string Kind);
